export default Object.freeze(
    {
        GET_ROUTES: "getRoutes",
        SET_ROUTES: "setRoutes",
        SET_ALLROUTES : "setAllRoutes",
        GET_ALLROUTES : "getAllRoutes",
        REGISTER_ROUTE: "resgisterRoute",
        GET_ROUTE: "getRoute",
        SET_ROUTE: "setRoute",
        MODIFY_ROUTE: "modifyRoute",
        REMOVE_ROUTE: "removeRoute",
        INITIATE_ROUTE: "intitiate",
        SET_INIT_ROUTE: "setInitRoute",
        GET_PLANS : "getPlans",
        SET_PLANS : "setPlans",
        SET_PLAN : "setPlans",
        SET_PLAN_MUTATION : "setPlansMutation",
        INIT_PLANS : "initPlans",
        INITIATE_PLANS: "initiatePlans",
        REMOVE_PLAN: "removePlan",
        REMOVE_PLAN_MUTAION: "removePlanMutation",
        MOVE_UP:"moveUpAction",
        MOVE_UP_MUTATION : "moveUpMutation",
        MOVE_DOWN:"moveDownAction",
        MOVE_DOWN_MUTATION : "moveDownMutation",
        REPRACE_ROUTE : "replaceRoute",
        REPLACE_ROUTE_MUTATATION: "replaceRouteMutation",
        SET_TOKENS: "setTokens",
        SET_ALLTOKENS_MUTATION: "setTokensMutation",
        SET_ACCESSTOKENS_MUTATION: "setAccessTokensMutation",
        SET_REFRESHTOKENS_MUTATION: "setRefreshTokensMutation",
        GET_CERT : "getCert",
        GET_CERT_MUTATION: "getCertMutation",
        LOGOUT: "logout",
        REMOVE_TOKENS: "removeTokens",
        CHECK_REFRESH_TOKEN_MUTATION : "checkRefreshTokenMutation",
        CHECK_REFRESH_TOKEN : "checkRefreshToken",
        FORCE_PLANLIST : "forcePlanList",
        FORCE_PLANLIST_MUTATION : "force_PlanListMutation",
        SET_STARTDATE: "setStartDate",
        SET_ENDDATE: "setEedDate",
        SET_STARTDATE_MUTATION: "setStartDateMutation",
        SET_ENDDATE_MUTATION: "setEedDateMutation",
        CHECK_REFRESH: "checkRefresh",
    }
);